# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.vestris.com
title: Vestris.com
email: dblock@vestris.com
author: Daniel Doubrovkine
description: Going boldly to where no man has gone before.
copyright: 'Copyright &copy; 2019 <a href="https://twitter.com/vestrisdotcom">Vestris, LLC</a>. All Rights Reserved.'
credits:

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    type: twitter
    url: https://twitter.com/vestrisdotcom
  - title: github
    type: github
    url: https://github.com/vestris
